name: Production - update the Search Graph with data from dataset 'Colonial Objects' in the Knowledge Graph

on:
  schedule:
    - cron: "35 3 * * *"

jobs:
  update-sg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - name: Iterate
        run: |
          ./packages/graph-creator/dist/cli.js sparql-iterate \
            --endpoint-url "${{ vars.SPARQL_ENDPOINT_KG_PRODUCTION }}" \
            --query-file ./packages/graph-creator/queries/production/colonial-objects/iterate.rq \
            --number-of-iris-per-request 10000 \
            --wait-between-requests 500 \
            --iri-file ./data/colonial-objects.txt
      - name: Generate
        run: |
          ./packages/graph-creator/dist/cli.js sparql-generate \
            --endpoint-url "${{ vars.SPARQL_ENDPOINT_KG_PRODUCTION }}" \
            --query-path ./packages/graph-creator/queries/production/colonial-objects/generate.rq \
            --number-of-resources-per-request 25 \
            --number-of-concurrent-requests 1 \
            --wait-between-requests 500 \
            --iri-file ./data/colonial-objects.txt \
            --rdf-file ./data/colonial-objects.nt
      - name: Upload
        run: |
          ./packages/graph-creator/dist/cli.js upload \
            --triplydb-instance-url "${{ vars.TRIPLYDB_INSTANCE_URL }}" \
            --triplydb-api-token "${{ secrets.TRIPLYDB_API_TOKEN }}" \
            --triplydb-account "${{ vars.TRIPLYDB_ACCOUNT_PRODUCTION }}" \
            --triplydb-dataset "${{ vars.TRIPLYDB_DATASET_SG_PRODUCTION }}" \
            --triplydb-service-name "search" \
            --triplydb-service-type "elasticsearch" \
            --rdf-file ./data/colonial-objects.nt \
            --graph-name "https://data.colonialcollections.nl/colonial-objects"
