name: Production - update the Knowledge Graph with data from the data registry

on:
  push:
    branches: ["main"]
    paths: ["packages/data-registry/data/production/**"]

jobs:
  update-kg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            production:
              - "packages/data-registry/data/production/**"
      # Run only if production files were changed
      - name: Update Knowledge Graph
        if: steps.changes.outputs.production == 'true'
        run: |
          ./packages/data-registry/dist/cli.js upload \
            --triplydb-instance-url "${{ secrets.TRIPLYDB_INSTANCE_URL }}" \
            --triplydb-api-token "${{ secrets.TRIPLYDB_API_TOKEN }}" \
            --triplydb-account "${{ secrets.TRIPLYDB_ACCOUNT_PRODUCTION }}" \
            --triplydb-dataset "${{ secrets.TRIPLYDB_DATASET_KG_PRODUCTION }}" \
            --triplydb-service-name "kg" \
            --triplydb-service-type "virtuoso" \
            --file-pattern "packages/data-registry/data/production/**/*.ttl"
