name: Production - update the Knowledge Graph when the Data Registry changes

on:
  push:
    branches: ["main"]
    paths: ["packages/data-registry/data/production/**"]

jobs:
  update-kg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - name: Update Knowledge Graph
        run: |
          ./packages/data-registry/dist/cli.js upload \
            --triplydb-instance-url "${{ vars.TRIPLYDB_INSTANCE_URL }}" \
            --triplydb-api-token "${{ secrets.TRIPLYDB_API_TOKEN }}" \
            --triplydb-account "${{ vars.TRIPLYDB_ACCOUNT_PRODUCTION }}" \
            --triplydb-dataset "${{ vars.TRIPLYDB_DATASET_KG_PRODUCTION }}" \
            --triplydb-service-name "kg" \
            --triplydb-service-type "virtuoso" \
            --file-pattern "packages/data-registry/data/production/**/*.ttl"
